url: "https://julesrx.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: "Jules Raffoux" # the name of your site, e.g. ACME Corp.
email: me@julesrx.fr
description: >- # this means to ignore newlines until "short_description:"
  DÃ©veloppeur full-stack chez bewease
short_description: DÃ©veloppeur Full Stack
long_description: >
  Joueur compÃ©titif, dÃ©veloppeur full-stack chez <a href="https://www.bewease.fr/" target="_blank">bewease</a>, et grand amateur de pÃ¢tes ğŸ
twitter_username: "julesrx__"
github_username:  "julesrx"
color: "2ecc71"

sass:
  style: compressed

timezone: Europe/Paris
encoding: utf-8