title: Jules Raffoux
email: julesraffoux@utila.io
description: >- # this means to ignore newlines until "short_description:"
  D√©veloppeur full-stack chez bewease
short_description: D√©veloppeur Full Stack
long_description: >
  Joueur comp√©titif, d√©veloppeur full-stack chez <a href="https://www.bewease.fr/" target="_blank">bewease</a>, et grand amateur de p√¢tes üçù
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://julesrx.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "julesrx__"
github_username:  julesrx
color: 2ecc71

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-coffeescript

sass:
  style: compressed

timezone: Europe/Paris
encoding: utf-8
